-- Gerado por scripts/import-prayers.mjs --emit-sql
-- Fonte: data/prayers-bulk.json (24 orações)
-- Rode no SQL Editor do Supabase com role que ignore RLS (ex.: postgres).

INSERT INTO public.prayers (title, text, category, tags, image_url, author_id, author_name, created_at, prayer_count, latin_text, parent_prayer_id, is_devotion)
VALUES
('Glória ao Pai', 'Glória ao Pai, e ao Filho, e ao Espírito Santo. Como era no princípio, agora e sempre. Amém.', 'Diárias', ARRAY['#trindade', '#louvor'], NULL, NULL, 'Tradição da Igreja', now(), 0, 'Gloria Patri, et Filio, et Spiritui Sancto. Sicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen.', NULL, false),
('Salve Rainha', 'Salve, Rainha, mãe de misericórdia, vida, doçura e esperança nossa, salve! A vós bradamos os degredados filhos de Eva; a vós suspiramos gemendo e chorando neste vale de lágrimas. Eia, pois, advogada nossa, esses vossos olhos misericordiosos a nós volvei, e depois deste desterro mostrai-nos Jesus, bendito fruto do vosso ventre, ó clemente, ó piedosa, ó doce sempre Virgem Maria. V. Rogai por nós, santa Mãe de Deus. R. Para que sejamos dignos das promessas de Cristo. Amém.', 'Marianas', ARRAY['#Maria', '#Rainha', '#antifona'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração a São Miguel Arcanjo', 'São Miguel Arcanjo, defendei-nos no combate, sede o nosso refúgio contra as maldades e ciladas do demônio. Ordene-lhe Deus, instantemente o pedimos, e vós, príncipe da milícia celeste, pela virtude divina, precipitai no inferno a Satanás e aos outros espíritos malignos, que andam pelo mundo para perdição das almas. Amém.', 'Santos', ARRAY['#SãoMiguel', '#proteção'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração do Anjo da Guarda', 'Santo Anjo do Senhor, meu zeloso guardador, se a ti me confiou a piedade divina, sempre me rege, guarda, governa, ilumina. Amém.', 'Diárias', ARRAY['#anjo', '#proteção'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Memorare', 'Lembrai-vos, ó piíssima Virgem Maria, que nunca se ouviu dizer que algum daqueles que por vós têm implorado o vosso socorro, tenha sido por vós desamparado. Animados com igual confiança, a vós recorremos, ó Mãe do Verbo encarnado, não desprezeis as nossas súplicas, mas dignai-vos de as ouvir propícia. Amém.', 'Marianas', ARRAY['#Maria', '#confiança'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Acto de Contrição', 'Senhor meu Jesus Cristo, Deus e homem verdadeiro, Criador e Redentor meu, por serdes vós quem sois, sumamente bom, e porque vos amo de todo o meu coração, e penso de vos ofender, pesa-me de todo o meu coração de vos ter ofendido; proponho firmemente, ajudado com a graça que me concedereis, emendar-me e nunca mais tornar a pecar. Peço-vos e espero que me perdoeis pelos vossos merecimentos e por intercessão da bem-aventurada Virgem Maria e de todos os santos. Amém.', 'Diárias', ARRAY['#penitência', '#perdão'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Acto de Fé', 'Meu Deus, eu creio firmemente todas as verdades que a Santa Igreja Católica crê e ensina, porque Vós as revelastes. Amém.', 'Diárias', ARRAY['#fé'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Acto de Esperança', 'Meu Deus, espero com firme confiança alcançar de vossa bondade a vida eterna e as graças necessárias para merecê-la, porque sois onipotente e fiel para cumprir as vossas promessas. Amém.', 'Diárias', ARRAY['#esperança'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Acto de Caridade', 'Meu Deus, amo-Vos sobre todas as coisas com todo o meu coração, porque sois infinitamente bom e digno de ser amado. Amém.', 'Diárias', ARRAY['#caridade', '#amor'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Começo das Leituras (Veni Sancte Spiritus)', 'Vinde, Espírito Santo, enchei os corações dos vossos fiéis e acendei neles o fogo do vosso amor. Enviai o vosso Espírito e tudo será criado, e renovareis a face da terra. Ó Deus, que instruístes os corações dos vossos fiéis com a luz do Espírito Santo; fazei-nos apreciar retamente todas as coisas segundo o mesmo Espírito, e gozar sempre da sua consolação. Por Cristo, Senhor nosso. Amém.', 'Diárias', ARRAY['#EspíritoSanto', '#oração'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Bênção antes das refeições', 'Abençoai, Senhor, estes alimentos, para que recebamos com gratidão o pão de cada dia. Por Cristo, Senhor nosso. Amém.', 'Momentos da Vida', ARRAY['#mesa', '#gratidão'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Ação de graças depois das refeições', 'Demos graças ao Senhor pelos benefícios recebidos. Demos graças a Deus. Ao Santíssimo e Diviníssimo Sacramento. Ao nome de Jesus. Ao Coração de Jesus. Por intercessão da Virgem Maria. Amém.', 'Momentos da Vida', ARRAY['#mesa', '#gratidão'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração pela paz', 'Senhor Jesus, Príncipe da Paz, fazei brotar a paz nos corações e sobre a face da terra. Concedei aos líderes sabedoria e aos povos união na justiça e na caridade. Por nosso Senhor Jesus Cristo. Amém.', 'Intenção Especial', ARRAY['#paz', '#mundo'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração pelos doentes', 'Ó bom Jesus, que curastes tantos enfermos, tende piedade deste vosso servo (desta vossa serva), aliviai o seu sofrimento e restaurai a saúde, se for para a sua alma. Por Cristo, Senhor nosso. Amém.', 'Momentos da Vida', ARRAY['#saúde', '#enfermos'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração pelos falecidos', 'Eterno Deus e Pai bondoso, acolhei na vossa luz o nosso irmão (nossa irmã) falecido(a). Concedei-lhe, pelos méritos de Jesus Cristo, o descanso eterno. Amém. Dai-lhe, Senhor, o descanso eterno, e brilhe para ele (ela) a luz perpétua. Descansem em paz. Amém.', 'Momentos da Vida', ARRAY['#falecidos', '#sufrágio'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração do Enfermo', 'Filho de Davi, tende piedade de mim. Jesus, manso e humilde de coração, fazei o meu coração semelhante ao vosso. Ó Jesus, pelas vossas chagas santas, salvai-me e guardai-me.', 'Momentos da Vida', ARRAY['#enfermo', '#confiança'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração a São José', 'Glorioso São José, esposo da Virgem Maria, obtende-me espírito de trabalho honesto e paz no lar; defendei a Santa Igreja e as famílias cristãs. Amém.', 'Santos', ARRAY['#SãoJosé', '#familia'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Ladainha — invocação breve', 'Senhor, tende piedade de nós. Cristo, tende piedade de nós. Senhor, tende piedade de nós. Santa Maria, rogai por nós. São José, rogai por nós. Todos os santos e santas de Deus, rogai por nós.', 'Marianas', ARRAY['#ladainha', '#intercessão'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oferecimento do dia', 'Senhor, ofereço-vos todas as obras deste dia: os trabalhos, alegrias e sofrimentos, em união com o vosso sacrifício na cruz, por minha salvação e pela de todos. Amém.', 'Diárias', ARRAY['#dia', '#oferecimento'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração do Terceiro, Sexto e Nono', '<b>O Terceiro:</b> Ó Verbo de Deus, que deste vida a todas as coisas, em vós é manifestada a vontade do Pai no Espírito Santo; purificai-nos de todo pecado e salvai-nos.<br/><br/><b>O Sexto:</b> Ó Cristo, Deus e homem, que destes alento aos enfermos, sede nosso descanso no meio do labor deste dia.<br/><br/><b>O Nono:</b> Misericordioso Salvador, que destes alívio aos cansados no fim do dia, concedei-nos a graça de uma vida santa e a paz na hora da morte.', 'Diárias', ARRAY['#horas', '#Jesus'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Súplica ao Coração de Jesus', 'Coração sacratíssimo de Jesus, tende piedade de nós.', 'Diárias', ARRAY['#CoraçãodeJesus', '#misericórdia'], NULL, NULL, 'Tradição da Igreja', now(), 0, 'Cor Iesu sacratissimum, miserere nobis.', NULL, false),
('Jaculatória de Jesus Misericordioso', 'Jesus misericordioso, piedade de nós e do mundo inteiro.', 'Diárias', ARRAY['#DivinaMisericórdia', '#jaculatória'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Oração por vocação e missão', 'Espírito Santo, despertai no coração da Igreja grandes vocações sacerdotais e religiosas. Fortalecei os batizados para serem sal e luz no mundo. Amém.', 'Intenção Especial', ARRAY['#vocação', '#Igreja'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false),
('Magnificat (breve)', 'A minh’alma engrandece ao Senhor, e o meu espírito exulta em Deus, meu Salvador, porque pôs os olhos na humildade de sua serva. Desde agora todas as gerações hão de chamar-me bem-aventurada, porque grandes coisas me fez o Poderoso, e santo é o seu nome.', 'Marianas', ARRAY['#Magnificat', '#louvor'], NULL, NULL, 'Tradição da Igreja', now(), 0, NULL, NULL, false);
